name: release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    # define multiple targets
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            executable: ntfd
            asset_name: ntfd-linux
          - os: windows-latest
            executable: ntfd.exe
            asset_name: ntfd-windows
          - os: macos-latest
            executable: ntfd
            asset_name: ntfd-macos

    # build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: enable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: build
        run: cargo build --release

      - name: Set enviroment for github-release
        run: |
          echo "RELEASE_TAG=$( echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

      - name: create archive
        run: |
          tar -czf "target/release/${{ matrix.asset_name }}-${RELEASE_TAG}.tar.gz" \
            -C target/release "${{ matrix.executable }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            target/release/${{ matrix.asset_name }}-${{ env.RELEASE_TAG }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
